Run script now generates obfuscated output, rerun output, and de-obfuscated output. Also runs/shows diff

diff --git a/mesa/src/LunarGLASS/test/run b/mesa/src/LunarGLASS/test/run
--- a/mesa/src/LunarGLASS/test/run
+++ b/mesa/src/LunarGLASS/test/run
@@ -20,20 +20,57 @@ function runTests {
     for t in ${TESTS[@]}; do
         printf "Running $t"
         LENSTR=$((${#t} + 8))
-        INDENTLVL=$((35 - $LENSTR))
-        GLSLLVL=39 # Magic number
+        INDENTLVL=$((37 - $LENSTR))
+        OBFUSCATE_INDENTLVL=$(($INDENTLVL + 5))
+        GLSLLVL=41 # Magic number
 
         # Run for TGSI
         printf "%${INDENTLVL}s" "TGSI "
-        $RUNCMD ${OPTIONS[@]} $TGSIOP $t > $t.stdout 2> $t.errout && echo -n "[OK]" \
+        $RUNCMD ${OPTIONS[@]} $TGSI_OP $t > $t.stdout 2> $t.errout && echo -n "[OK]" \
             || (echo "[FAIL] " ; tail -n 1 $t.errout ; printf "%${GLSLLVL}s" " ")
         cat $t.errout $t.stdout > tgsi/$t.out
 
         # Run for GLSL
-         echo -n "        GLSL "
-        $RUNCMD ${OPTIONS[@]} $GLSLOP $t > $t.stdout 2> $t.errout  && echo "[OK]" \
+        echo -n "        GLSL "
+        $RUNCMD ${OPTIONS[@]} $GLSL_OP $t > $t.stdout 2> $t.errout  && echo "[OK]" \
             || (echo "[FAIL] " ; tail -n 1 $t.errout)
         cat $t.errout $t.stdout > glsl/$t.out
+
+        printf "    Obfuscating:                "
+
+        # Run obfuscated TGSI
+        printf "TGSI "
+        $RUNCMD ${OPTIONS[@]} $TGSI_OP $OBFUSCATE_OP $t > $t.stdout 2> $t.errout && echo -n "[OK]" \
+            || (echo "[FAIL] " ; tail -n 1 $t.errout ; printf "%${GLSLLVL}s" " ")
+        cat $t.errout $t.stdout > tgsi/$t.out.obfuscated
+
+        # Run obfuscated GLSL
+        echo -n "        GLSL "
+        $RUNCMD ${OPTIONS[@]} $GLSL_OP $OBFUSCATE_OP $t > $t.stdout 2> $t.errout && echo "[OK]" \
+            || (echo "[FAIL] " ; tail -n 1 $t.errout)
+        cat $t.errout $t.stdout > glsl/$t.out.obfuscated
+
+        printf "    Feeding back in:                     "
+        printf "        GLSL "
+        ($RUNCMD $GLSL_OP $t > $t.stdout.frag 2> $t.errout && $RUNCMD $GLSL_OP $t.stdout.frag > $t.stdout 2> $t.errout && echo "[OK]") \
+            || (echo "[FAIL] " ; tail -n 1 $t.errout)
+        cat $t.stdout > glsl/$t.out.rerun
+
+        printf "    De-obfuscating:                      "
+        printf "        GLSL "
+        ($RUNCMD $GLSL_OP $OBFUSCATE_OP $t > $t.stdout.obfuscated.frag 2> $t.errout && $RUNCMD $GLSL_OP $t.stdout.obfuscated.frag > $t.stdout 2> $t.errout && echo "[OK]") \
+            || (echo "[FAIL] " ; tail -n 1 $t.errout)
+        cat $t.stdout > glsl/$t.out.de-obfuscated
+
+        # Diff them
+        printf "    Diffing rerun and de-obfuscate:      "
+        printf "        GLSL "
+        (diff --side-by-side --suppress-common-lines glsl/$t.out.rerun glsl/$t.out.de-obfuscated > $t.diff && echo "[OK]") \
+            || (echo "[FAIL]" ; cat $t.diff)
+
+        echo
+        rm $t.stdout.obfuscated.frag
+        rm $t.stdout.frag
         rm $t.stdout $t.errout
     done
 }
@@ -46,8 +83,9 @@ function showHelp {
 # Default is for windows
 RUNCMD=../../glsl/Debug/StandAlone.exe
 OPTIONS=(-d)
-TGSIOP="--tgsi"
-GLSLOP="--glsl"
+TGSI_OP="--tgsi"
+GLSL_OP="--glsl"
+OBFUSCATE_OP="-f"
 # Command-line argument Handling
 
 # No arguments passed
