run script prints error output on it's own line

diff --git a/mesa/src/LunarGLASS/test/run b/mesa/src/LunarGLASS/test/run
--- a/mesa/src/LunarGLASS/test/run
+++ b/mesa/src/LunarGLASS/test/run
@@ -25,13 +25,13 @@ function runTests {
         # Run for TGSI
         printf "%${INDENTLVL}s" "TGSI "
         $RUNCMD ${OPTIONS[@]} $TGSIOP $t > $t.stdout 2> $t.errout && echo -n "[OK]" \
-            || (tail -n 1 $t.errout ; printf "%${GLSLLVL}s" " ")
+            || (echo "[FAIL] " ; tail -n 1 $t.errout ; printf "%${GLSLLVL}s" " ")
         cat $t.errout $t.stdout > tgsi/$t.out
 
         # Run for GLSL
          echo -n "        GLSL "
         $RUNCMD ${OPTIONS[@]} $GLSLOP $t > $t.stdout 2> $t.errout  && echo "[OK]" \
-            || (echo -n " [FAIL] " ; tail -n 1 $t.errout)
+            || (echo "[FAIL] " ; tail -n 1 $t.errout)
         cat $t.errout $t.stdout > glsl/$t.out
         rm $t.stdout $t.errout
     done
